type NerdcastCard = {
  id: string;
  name: string;
  originalSrc: string;
  signedOn: Date | null;
  signedLocation: string | null;
  signedSrc: string | null;
};

export const DECK_LIST: NerdcastCard[] = [
  {
    id: "card-01",
    name: "Alottoni",
    originalSrc: "/images/card/nerdcast-k-alottoni.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-02",
    name: "Azaghal",
    originalSrc: "/images/card/nerdcast-k-azaghal.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-03",
    name: "JP",
    originalSrc: "/images/card/nerdcast-k-jp.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-04",
    name: "Sr. K",
    originalSrc: "/images/card/nerdcast-k-srk.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-05",
    name: "Sra. Jovem Nerd",
    originalSrc: "/images/card/nerdcast-q-srajovemnerd.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-06",
    name: "Portuguesa",
    originalSrc: "/images/card/nerdcast-q-portuguesa.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-07",
    name: "Francine",
    originalSrc: "/images/card/nerdcast-q-francine.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-08",
    name: "Ruiva",
    originalSrc: "/images/card/nerdcast-q-ruiva.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-09",
    name: "Blue Hand",
    originalSrc: "/images/card/nerdcast-j-bluehand.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-10",
    name: "Eduardo Spohr",
    originalSrc: "/images/card/nerdcast-j-eduardospohr.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-11",
    name: "Guga Ferrari",
    originalSrc: "/images/card/nerdcast-j-gugaferrari.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-12",
    name: "Tucano",
    originalSrc: "/images/card/nerdcast-j-tucano.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-13",
    name: "Android",
    originalSrc: "/images/card/nerdcast-a-android.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-14",
    name: "Guilherme Briggs",
    originalSrc: "/images/card/nerdcast-a-briggs.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-15",
    name: "Carlos Voltor",
    originalSrc: "/images/card/nerdcast-a-carlosvoltor.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-16",
    name: "Nick Ellis",
    originalSrc: "/images/card/nerdcast-a-nickellis.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-17",
    name: "Fabio Yabu",
    originalSrc: "/images/card/nerdcast-joker-fabioyabu.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-18",
    name: "Tresdê",
    originalSrc: "/images/card/nerdcast-joker-tresde.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
  {
    id: "card-19",
    name: "Amigo Imaginário",
    originalSrc: "/images/card/nerdcast-amigoimaginario.webp",
    signedOn: null,
    signedLocation: null,
    signedSrc: null,
  },
];
